# Generated by Django 5.0.1 on 2024-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('nota', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_remitente', models.CharField(max_length=100)),
                ('rut_remitente', models.CharField(max_length=12)),
                ('direccion_remitente', models.CharField(max_length=255)),
                ('email_remitente', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_remitente', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('rut_destinatario', models.CharField(max_length=12)),
                ('direccion_destinatario', models.CharField(max_length=255)),
                ('email_destinatario', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_destinatario', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_paquete', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=2)),
                ('tipo_envio', models.CharField(choices=[('normal', 'Envío Normal'), ('express', 'Envío Express 24hrs')], max_length=10)),
                ('pagado', models.BooleanField(default=False)),
                ('por_pagar', models.BooleanField(default=False)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('session_id', models.CharField(blank=True, max_length=150, null=True)),
                ('buy_order', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estado_envio', models.CharField(choices=[('completado', 'Completado'), ('en_camino', 'En Camino'), ('en_proceso', 'En Proceso')], max_length=10)),
            ],
        ),
    ]
