# Generated by Django 5.0.1 on 2024-07-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado_envio',
            field=models.CharField(choices=[('completado', 'Completado'), ('en_camino', 'En Camino'), ('en_proceso', 'En Proceso')], default='en_proceso', max_length=10),
        ),
    ]
