# Generated by Django 5.0.1 on 2024-05-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
