# Generated by Django 5.0.1 on 2024-05-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_transaccion_id_transaccion_buy_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='buy_order',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='session_id',
        ),
    ]
